### ISSUE TITLE
Error Native linking failed after update xamarin.ios

### ISSUE THREAD

**Issue by fuadhamidan** [jingliancui/ZYBannerView_Xamarin#1]
Today I update xamarin.ios in VS for mac. And can't build the application because it gets an error like in the screenshot.

<img width="877" alt="screen shot 2017-08-15 at 2 11 48 pm" src="https://user-images.githubusercontent.com/517472/29305662-0fe89480-81c4-11e7-8e0e-7273dc43f0c4.png">

The same thing happened when build a demo app.

**Comment by jingliancui** [comment]
Hello I had fix the issue . 

VS throw this error because the `interface ZYBannerViewLib
` in the ApiDefinition.cs file . Just Delete this interface ,and the app will run it successfully.


You can download the project and try it again.
Thanks.
